services:
  api:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: komirka
      MYSQL_USER: komirka
      MYSQL_PASSWORD: komirka
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"