services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: komirka
      MYSQL_USER: komirka
      MYSQL_PASSWORD: komirka
      MYSQL_ROOT_PASSWORD: root
    networks:
      - komirka-net

  api:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "server=db;database=komirka;user=komirka;password=komirka"
    depends_on:
      - db
    networks:
      - komirka-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - komirka-net

networks:
  komirka-net:
    driver: bridge
